app/models.py
from app import db, login
from flask import current_app
from datetime import datetime
from time import time
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from hashlib import md5
import jwt


followers = db.Table("followers",
                    db.Column("follower_id", db.Integer(), db.ForeignKey('user.id')),
                    db.Column("followed_id", db.Integer(), db.ForeignKey('user.id')))


class User(UserMixin, db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.String(20), index=True, unique=True)
    email = db.Column(db.String(60), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    posts = db.relationship('Post', backref='author', lazy='dynamic')
    about_me = db.Column(db.String(140))
    last_seen = db.Column(db.DateTime(), default=datetime.utcnow)
    followed = db.relationship('User', secondary=followers,
                               primaryjoin=(followers.c.follower_id == id),
                               secondaryjoin=(followers.c.followed_id == id),
                               backref=db.backref('followers', lazy='dynamic'), lazy='dynamic')

    def __repr__(self):
        return '<User : {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(digest, size)

    def is_following(self, user):
        return self.followed.filter(followers.c.followed_id == user.id).count() > 0

    def follow(self, user):
        if not self.is_following(user):
            self.followed.append(user)

    def unfollow(self, user):
        if self.is_following(user):
            self.followed.remove(user)

    def followed_posts(self):
        return Post.query.join(followers,
                               (followers.c.followed_id == Post.user_id).filter(
                                followers.c.follower_id == self.id).order_by(Post.timestamp.desc()))

    def get_reset_password_token(self, expire_in=600):
        return jwt.encode(
            {'reset_password': self.id, 'exp': time() + expire_in},
              current_app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')

    @staticmethod
    def verify_reset_password_token(token):
        try:
            id = jwt.decode(token, current_app.config['SECRET_KEY'], algorithms=['HS256'])['reset_password']
        except:
            return
        return User.query.get(id)


class Post(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime(), default=datetime.utcnow)
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Post : {}>'.format(self.body)


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/core/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, TextAreaField
from wtforms.validators import DataRequired, Length, ValidationError
from app.models import User


class EditProfileForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    about_me = TextAreaField("About Me", validators=[Length(min=0, max=140)])
    submit = SubmitField("Edit")

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError("Username already used, please use another one.")


class PostForm(FlaskForm):
    post = TextAreaField("What's up ?", validators=[Length(min=0, max=140)])
    submit = SubmitField("Post")

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_moment import Moment
from flask_mail import Mail
from config import Config


bootstrap = Bootstrap()
login = LoginManager()
login.login_view = "auth.login"
db = SQLAlchemy()
migrate = Migrate()
moment = Moment()
mail = Mail()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    bootstrap.init_app(app)
    login.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    moment.init_app(app)
    mail.init_app(app)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.core import bp as core_bp
    app.register_blueprint(core_bp)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    return app


from app import models

app/core/__init__.py
from flask import Blueprint

bp = Blueprint("core", __name__)

from app.core import routes

app/core/routes.py
from flask import render_template, flash, request, redirect, url_for
from app.core import bp
from app import db
from flask_login import login_required, current_user
from app.core.forms import EditProfileForm, PostForm
from datetime import datetime
from app.models import User, Post


@bp.route('/', methods=['POST', 'GET'])
@bp.route('/index', methods=['POST', 'GET'])
@login_required
def index():
    form = PostForm()
    posts = Post.query.order_by(Post.timestamp.desc()).all()
    if form.validate_on_submit():
        post = Post(body=form.post.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('core.index'))
    return render_template('core/index.html', title='Home', form=form, posts=posts)


@bp.route('/explore')
@login_required
def explore():
    posts = Post.query.order_by(Post.timestamp.desc()).all()
    return render_template('core/index.html', title='Explore', posts=posts)


@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()


@bp.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts.order_by(Post.timestamp.desc()).all()
    return render_template('core/user.html', title="Profile", user=user, posts=posts)


@bp.route('/edit_profile', methods=['POST', 'GET'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash("Your changes have been saved.")
        return redirect(url_for('core.user', username=current_user.username))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('core/edit_profile.html', title="Edit Profile", form=form)


@bp.route('/user/<username>/follow')
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user == current_user:
        flash('You cannot follow yourself.')
        return redirect(url_for('core.user', username=current_user.username))
    if user is None:
        flash('User {} not found.'.format(user.username))
        return redirect(url_for('core.index'))
    current_user.follow(user)
    db.session.commit()
    return redirect(url_for('core.user', username=user.username))


@bp.route('/user/<username>/unfollow')
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user == current_user:
        flash('You cannot unfollow yourself.')
        return redirect(url_for('core.user', username=current_user.username))
    if user is None:
        flash('User {} not found.'.format(user.username))
        return redirect(url_for('core.index'))
    current_user.unfollow(user)
    db.session.commit()
    return redirect(url_for('core.user', username=user.username))

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}
    {% if title %}
        HiGuys - {{ title }}
    {% else %}
        Welcome to HiGuys
    {% endif %}
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('core.index') }}">HiGuys</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('core.index') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('core.explore') }}">explore</a>
                </li>
            </ul>
            <div class="container">
                <ul class="navbar-nav justify-content-end">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link btn btn-primary text-white mr-2" role="button"
                           href="{{ url_for('core.user', username=current_user.username) }}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-outline-secondary" role="button"
                           href="{{ url_for('auth.logout') }}">Sign Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link btn btn-primary text-white mr-2" role="button"
                           href="{{ url_for('auth.login') }}">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-outline-secondary" role="button"
                           href="{{ url_for('auth.register') }}">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav><br>
{% endblock %}


{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-info" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {% block app_content %}{% endblock %}
    </div>
{% endblock %}


{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
{% endblock %}

app/templates/core/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block app_content %}
    <h2>Edit Profile</h2>
    <div class="form-group row">
        <div class="col-sm-5">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/core/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block app_content %}
    <h2>Hi {{ current_user.username }}!</h2>
    {% if form %}
    <div class="form-group row">
        <div class="col-sm-12">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
    {% endif %}

    {% for post in posts %}
        {% include "core/post/_post.html" %}
    {% endfor %}
{% endblock %}

app/templates/core/post/_post.html
<table class="table table-hover">
    <tr valign="top">
        <td width="64px">
            <a href="{{ url_for('core.user', username=post.author.username) }}">
            <img src="{{ post.author.avatar(64) }}"></a>
        </td>
        <td>
            <p>
                <a href="{{ url_for('core.user', username=post.author.username) }}">
                    <b>{{ post.author.username }}</b></a>
                {{ moment(post.timestamp).fromNow() }}
            </p>
            <p>{{ post.body }}</p>
        </td>
    </tr>
</table>

app/templates/core/user.html
{% extends "base.html" %}

{% block app_content %}
    <table class="table table-hover">
        <tr valign="top">
            <td width="150px"><img src="{{ user.avatar(150) }}"></td>
            <td>
                <h2>User : {{ user.username }}</h2>
                {% if user.about_me %}
                <p>About Me : {{ user.about_me }}</p>
                {% endif %}
                {% if user.last_seen %}
                <p>Last Seen : {{ moment(user.last_seen).format('LLL') }}</p>
                {% endif %}
                <p>Followers : {{ user.followers.count() }}, Following : {{ user.followed.count() }}</p>
                {% if current_user == user %}
                <a class="btn btn-primary" role="button" href="{{ url_for('core.edit_profile') }}">Edit Profile</a>
                {% else %}
                    {% if current_user.is_following(user) %}
                    <a class="btn btn-secondary" role="button"
                       href="{{ url_for('core.unfollow', username=user.username) }}">Unfollow</a>
                    {% else %}
                    <a class="btn btn-primary" role="button"
                       href="{{ url_for('core.follow', username=user.username) }}">Follow</a>
                    {% endif %}
                {% endif %}
            </td>
        </tr>
    </table>

    {% for post in posts %}
        {% include "core/post/_post.html" %}
    {% endfor %}
{% endblock %}